### PR TITLE
/Dev/fpoppinga/bandit

### PR DESCRIPTION
**Pull request by fpoppinga**
this is required for https://github.com/HULKs/nao/pull/2071

### CODE REVIEW

**Comment by fpoppinga** [comment]
I also rebased onto master. IDK if that's a great idea.

**Comment by rkost** [comment]
@nagua any thoughts? I like the idea of having bandit as a test framework. Also should be just merge the opencv branch into our master branch?

@fpoppinga I guess the cleaner way would be to update our master and then rebase your branch on that.

**Comment by fpoppinga** [comment]
@rkost probably.

**Comment by fpoppinga** [comment]
The biggest problem seems to be that @nagua 's opencv branch contains ca. 200 commits which are not in microsoft's master...

**Comment by nagua** [comment]
The opencv branch is copied from a PR on the official repository. So opencv will be merged eventually. The we can use the official master and just add our own bandit branch on top of that.

**Comment by nagua** [comment]
Ok, I had the same problem today... I created a new branch hulksModifications for that now. I will close this PR and open a new one for the new branch.

**Comment by nagua** [comment]
Ok, I cherry-picked the commit and pushed it to the branch.

**Pull request closed without merging**
